



name: Extraer Boxscore ACB 2025-26

on:
  workflow_dispatch:
  schedule:
    # OCTUBRE a MARZO (UTC+1)
    - cron: '30 18-22 * 10-12,1-3 6'  # Sábados
    - cron: '30 12-22 * 10-12,1-3 0'  # Domingos

    # ABRIL a SEPTIEMBRE (UTC+2)
    - cron: '30 17-21 * 4-9 6'  # Sábados
    - cron: '30 11-21 * 4-9 0'  # Domingos

jobs:
  Get-Boxscore-ACB:
    name: Actualizar Boxscore ACB 
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ACB_KEY: ${{ secrets.ACB_KEY }}
      ACB_TOKEN: ${{ secrets.ACB_TOKEN }}
      API_URL: ${{ secrets.API_URL }}
      PBP: ${{ secrets.PBP }}
    steps:
      - uses: actions/checkout@v3  
      
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
          r-version: 'release'
          
      - name: Install libcurl and libssl on Linux
        run: sudo apt-get -y install libcurl4-openssl-dev 
        shell: bash
        
      - name: Cache CRAN packages
        uses: actions/cache@v3 
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/DESCRIPTION') }}
          restore-keys: ${{ runner.os }}-r-
          
      - name: Install CRAN packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with: 
          packages: tidyverse, httr, janitor, jsonlite, lubridate
          
      - name: Run R script
        run: Rscript scripts/main_acb_update.R
        shell: bash

      - name: Commit changes in data folder
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/*.csv
          git diff --cached --quiet || git commit -m "Auto-update: Boxscore ACB 2025-26"
        shell: bash

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
